### ISSUE TITLE
missing lib/src/network_printer.dart

### ISSUE THREAD

**Issue by tungpham6195** [CastawayLabs/dart-escpos#1]
hi @matejkramny , there are missing `network_printer.dart` file, please check it

**Comment by matejkramny** [comment]
You're right, will add this back from the repo

Thanks

**Comment by tungpham6195** [comment]
can i know when you will add it back?, you should keep the previous fork from `andrey-ushakov/esc_pos_printer`, because someone have been using it 😂

**Comment by matejkramny** [comment]
Yeah that makes sense, but there's no point keeping 2 separate packages/repos imo

It should be fairly easy to migrate just by renaming the import paths

**Comment by tungpham6195** [comment]
in my case, I have been using your previous fork, it has just been removed after I replaced by your package and got the issue, I wanna rollback but not able to do it 😂

sure, I will check it again tmr

thanks so much @matejkramny

**Comment by matejkramny** [comment]
This is in version 5.0.2
